### PR TITLE
_r_a_j_a_v_.py

### PR DESCRIPTION
**Pull request by saaho-max**

### CODE REVIEW

**Comment by fabriziodsp-ransom** [comment]
What is rajav? And what can your code actually implement instead of just the variable's name change?

**Comment by fabriziodsp-ransom** [comment]
And by the way. There's an error at line 32. You've mistaken the comma.

**Review by fabriziodsp-ransom — COMMENTED** [review]
What is rajav? And what can your code actually implement instead of just the variable's name change?
Btw, there's an error at line 33. Apparently you've mistaken a comma.

**Comment by vlknbrn** [comment]
hi friend, how can i  use with proxy  i dont know. instagram.py username /proxylist/passlist -m 2 like that or can you write to me right pls

**Pull request closed without merging**
