### PR TITLE
  1  git clone https://github.com/thelinuxchoice/instashell.git

### PR DESCRIPTION
**Pull request by mohammad1360**

### CODE REVIEW

**Comment by mohammad1360** [comment]
| git clone https://github.com/thelinuxchoice/instashell.git

**Comment by yas137797** [comment]
git clone Link

**Comment by Btyface** [comment]
Ok

Pada tanggal Rab, 23 Okt 2019 13.00, yas137797 <notifications@github.com>
menulis:

**Comment by kekuskan554** [comment]
instagram : name mhjhjml HACKER PLEASE

**Pull request closed without merging**
