### PR TITLE
instagram.py

### PR DESCRIPTION
**Pull request by Masterdhruv**

### CODE REVIEW

**Comment by Shervin2020** [comment]
hi

**Comment by Michel762** [comment]
can you help me hack an Instagram account

**Comment by tennokuarastoru** [comment]
stupid commit, stealing credit eh? n00b

**Review by c1hackzz — APPROVED** [review]

**Comment by Shubh-debug** [comment]
Unsubscribe

**Review by palyaka — APPROVED** [review]

**Comment by Eggstatic-H** [comment]
somebody provide me the tool link, it's not there idk why

**Comment by ANANYMOS6** [comment]
hy

**Pull request closed without merging**
