### PR TITLE
Update display.py

### PR DESCRIPTION
**Pull request by janesmithgirl**

### CODE REVIEW

**Review by searchformyusername — COMMENTED** [review]
this is bad `*_*`

**Comment by wdodsalman** [comment]
[!] Invalid path to password list

C:\Users\NS\Desktop\Instagram>

**Comment by babangBob** [comment]
-_-

**Comment by wdodsalman** [comment]
[!] Invalid path to password list

C:\Users\NS\Desktop\Instagram>
  how to fix this

**Pull request closed without merging**
