### PR TITLE
Password

### PR DESCRIPTION
**Pull request by Stongboynot**
Date: 12/28/2018
# Author: Mohamed
# Description: Password manager

from time import sleep
from hashlib import sha256
from sys import version_info
from lib.display import Display
from lib.database import Session
import io

class PasswordManager(object):
    def __init__(self, username, passlist_path, max_passwords, display):
        self.passlist = []
        self.session = None
        self.resume = False
        self.is_alive = True
        self.is_read = False
        self.display = display
        self.fingerprint = None
        self.username = username
        self.passwords_removed = 0
        self.passlist_path = passlist_path
        self.max_passwords = max_passwords
        Display.total_lines = self.count_lines()

    @property
    def list_size(self):
        return len(self.passlist)

    def list_add(self, password):
        if not password in self.passlist:
            self.passlist.append(password)

    def list_remove(self, password):
        if password in self.passlist:
            self.attempts += 1
            self.passlist.pop(self.passlist.index(password))
            self.session.write(self.attempts, self.passlist)

    def count_lines(self):
        lines = 0

        fingerprint = (
            sha256(self.username.lower().strip().encode()).hexdigest().encode()
        )

        self.display.info("Reading wordlist ...")

        with io.open(self.passlist_path, mode="rb") as f:

            for data in f:
                lines += 1
                chunk = sha256(data).hexdigest().encode()
                fingerprint = sha256(fingerprint + chunk).hexdigest().encode()

        self.fingerprint = fingerprint
        self.session = Session(self.fingerprint)

        return lines

    def read(self):
        attempts = 0
        with io.open(
            self.passlist_path, mode="rt", encoding="utf-8"
        ) as passlist:

            for password in passlist:
                if not self.is_alive:
                    break

                if self.resume:
                    self.attempts, self.passlist = self.session.read()

                    if attempts < (self.attempts + self.list_size):
                        attempts += 1
                        continue
                    else:
                        self.resume = False

                password = (
                    password.replace("\n", "")
                    .replace("\r", "")
                    .replace("\t", "")
                )

                if self.list_size < self.max_passwords:
                    self.list_add(password)
                else:
                    while (
                        self.list_size >= self.max_passwords and self.is_alive
                    ):
                        sleep(0.5)

                    if self.is_alive:
                        self.list_add(password)
                        self.session.write(self.attempts, self.passlist)

        if self.is_alive:
            self.is_read = True

    @property
    def attempts(self):
        return self.passwords_removed

    @attempts.setter
    def attempts(self, n):
        self.passwords_removed = n

    def start(self):
        self.read()

    def stop(self):
        self.is_alive = False
With maruf

### CODE REVIEW

**Comment by Hosseinf2012** [comment]
What's that code? I don't know what i should do?

Sent from Yahoo Mail on Android 
 
  On Sun, Feb 5, 2023 at 11:02, ***@***.***> wrote:   
Date: 12/28/2018

Author: Mohamed

Description: Password manager

from time import sleep
from hashlib import sha256
from sys import version_info
from lib.display import Display
from lib.database import Session
import io

class PasswordManager(object):
def init(self, username, passlist_path, max_passwords, display):
self.passlist = []
self.session = None
self.resume = False
self.is_alive = True
self.is_read = False
self.display = display
self.fingerprint = None
self.username = username
self.passwords_removed = 0
self.passlist_path = passlist_path
self.max_passwords = max_passwords
Display.total_lines = self.count_lines()
@property
def list_size(self):
    return len(self.passlist)

def list_add(self, password):
    if not password in self.passlist:
        self.passlist.append(password)

def list_remove(self, password):
    if password in self.passlist:
        self.attempts += 1
        self.passlist.pop(self.passlist.index(password))
        self.session.write(self.attempts, self.passlist)

def count_lines(self):
    lines = 0

    fingerprint = (
        sha256(self.username.lower().strip().encode()).hexdigest().encode()
    )

    self.display.info("Reading wordlist ...")

    with io.open(self.passlist_path, mode="rb") as f:

        for data in f:
            lines += 1
            chunk = sha256(data).hexdigest().encode()
            fingerprint = sha256(fingerprint + chunk).hexdigest().encode()

    self.fingerprint = fingerprint
    self.session = Session(self.fingerprint)

    return lines

def read(self):
    attempts = 0
    with io.open(
        self.passlist_path, mode="rt", encoding="utf-8"
    ) as passlist:

        for password in passlist:
            if not self.is_alive:
                break

            if self.resume:
                self.attempts, self.passlist = self.session.read()

                if attempts < (self.attempts + self.list_size):
                    attempts += 1
                    continue
                else:
                    self.resume = False

            password = (
                password.replace("\n", "")
                .replace("\r", "")
                .replace("\t", "")
            )

            if self.list_size < self.max_passwords:
                self.list_add(password)
            else:
                while (
                    self.list_size >= self.max_passwords and self.is_alive
                ):
                    sleep(0.5)

                if self.is_alive:
                    self.list_add(password)
                    self.session.write(self.attempts, self.passlist)

    if self.is_alive:
        self.is_read = True

@property
def attempts(self):
    return self.passwords_removed

@attempts.setter
def attempts(self, n):
    self.passwords_removed = n

def start(self):
    self.read()

def stop(self):
    self.is_alive = False

With maruf

You can view, comment on, or merge this pull request online at:

  https://github.com/Bitwise-01/Instagram-/pull/216

Commit Summary
   
   - 113a968 Password 

File Changes 
 
(1 file)
   
   -  M lib/password_manager.py (1) 

Patch Links:
   
   - https://github.com/Bitwise-01/Instagram-/pull/216.patch
   - https://github.com/Bitwise-01/Instagram-/pull/216.diff

**Comment by eneshanxs** [comment]
thank you for your help, where can I reach you except by mail ?

5 Şub 2023 Pzr 10:40 tarihinde Hosseinf2012 ***@***.***> şunu
yazdı:

> What's that code? I don't know what i should do?
>
> Sent from Yahoo Mail on Android
>

**Comment by Hosseinf2012** [comment]
Hello.Thank you for your reply. But  how can I use this code?Can you hack this ID your ***@***.***_shojaei86Instagram

Sent from Yahoo Mail on Android 
 
  On Mon, Feb 13, 2023 at 16:17, ***@***.***> wrote:   

thank you for your help, where can I reach you except by mail ?

5 Şub 2023 Pzr 10:40 tarihinde Hosseinf2012 ***@***.***> şunu
yazdı:

> What's that code? I don't know what i should do?
>
> Sent from Yahoo Mail on Android
>

**Comment by eneshanxs** [comment]
Hello, where can I run this code, how does it work?

13 Şub 2023 Pzt 16:33 tarihinde Hosseinf2012 ***@***.***>
şunu yazdı:

> Hello.Thank you for your reply. But  how can I use this code?Can you hack
> this ID your ***@***.***_shojaei86Instagram
>
> Sent from Yahoo Mail on Android
>

**Comment by eneshanxs** [comment]
<!--
/* Font Definitions */
@font-face
	{font-family:"Cambria Math";
	panose-1:2 4 5 3 5 4 6 3 2 4;}
@font-face
	{font-family:Calibri;
	panose-1:2 15 5 2 2 2 4 3 2 4;}
/* Style Definitions */
p.MsoNormal, li.MsoNormal, div.MsoNormal
	{margin:0cm;
	font-size:11.0pt;
	font-family:"Calibri",sans-serif;}
a:link, span.MsoHyperlink
	{mso-style-priority:99;
	color:blue;
	text-decoration:underline;}
.MsoChpDefault
	{mso-style-type:export-only;}
@page WordSection1
	{size:612.0pt 792.0pt;
	margin:70.85pt 70.85pt 70.85pt 70.85pt;}
div.WordSection1
	{page:WordSection1;}

**Comment by za** [comment]
Hi @Bitwise-01 I think this PR is not relevant. IMHO, we may close/reject the PR.

**Comment by Hosseinf2012** [comment]
Hello. I didnt understand what you say. I only want you to help me and hack an instagram account.I need her ***@***.***_shojaei86
Sent from Yahoo Mail on Android 
 
  On Wed, Feb 22, 2023 at 9:07, ***@***.***> wrote:   


Hi @Bitwise-01 I think this PR is not relevant. IMHO, we may close/reject the PR.

**Comment by za** [comment]
Hi @Hosseinf2012 This is a git repo where people put their code. It's not a place to ask someone to crack someone's instagram account.

**Comment by Hosseinf2012** [comment]
Sorry. Thank you. 

Sent from Yahoo Mail on Android 
 
  On Wed, Feb 22, 2023 at 11:29, ***@***.***> wrote:   


Hi @Hosseinf2012 This is a git repo where people put their code. It's not a place to ask someone to crack someone's instagram account.

**Comment by dannykardienaal** [comment]
--git a/lib/password_manager.py b/lib/password_manager.py
index cda12ee..ada47a1 100644
--- a/lib/password_manager.py
+++ b/lib/password_manager.py
@@ -113,3 +113,4 @@ def start(self):

**Pull request closed without merging**
